### ISSUE TITLE
Unable to disable default onTextInput handlers

### ISSUE THREAD

**Issue by eguitarz** [bustlelabs/mobiledoc-kit#480] opened 2016-08-31 06:59 UTC
Default textInputHandlers are nice but I found there's no public way to disable or override them.

For now I'm doing this to disable default handlers:
```
editor._eventManager._textInputHandler.destroy();
```

But there should be a public method in editor to do this. Maybe `resetTextInputHandlers()`?

**Comment by bantic** [comment] 2016-08-31 15:11
Duplicate of #191, which I'm closing in favor of this issue since the discussion there references a style of adding expansions that no longer exists.
I'd be in favor of adding a `resetTextInputHandlers` since that seems like it would solve your immediate use case. I have a small amount of hesitation because it's not clear how much "core" functionality is or will be handled by those text input handlers.
As mentioned in #191, exporting the text handlers by name would make it easy to selectively remove them, e.g. `unregisterTextInputHandler('heading')`.
Perhaps `unregisterAllTextInputHandlers` and `unregisterTextInputHandler(name)` are both worth adding?At the moment there are [only three](https://github.com/bustlelabs/mobiledoc-kit/blob/master/src/js/editor/text-input-handlers.js#L54-L78): unordered list, ordered list, and heading.

**Comment by eguitarz** [comment] 2016-09-01 01:43
`unregisterAllTextInputHandlers` and `unregisterTextInputHandler(name)` sounds good! Since `unregisterTextInputHandler(name)` will require every handler provides a name, we probably can implement `unregisterAllTextInputHandlers` as first step. How do you think? (I understand you have many features to do, so I'm fine if you need my help on this.)

**Comment by bantic** [comment] 2016-09-01 14:29
Yeah, if you have a chance to make a PR I'd be happy to merge it. I think we can both add the unregister all functionality and the unregister by name, we'll need to add names for the (3) existing input handlers. 3rd-party handlers can continue to be unnamed for now (they just won't be individually removable yet). After this lands we can add a deprecation for unnamed handlers. 

--
twitter.com/bantic

**Comment by eguitarz** [comment] 2016-09-01 18:09
Will make a PR by this weekend.

**Closed** 2016-09-06 14:27 UTC
